environment:
  PYTHON_HOME: "C:\\Python37"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
      CONAN_BUILD_TYPES: Debug
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_BUILD_TYPES: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16
      CONAN_BUILD_TYPES: Debug

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip install bincrafters_package_tools
  - conan user # It creates the conan data directory

build_script:
  - bincrafters-package-tools --auto
